### ISSUE TITLE
Can we have builds to go along with the updates?

### ISSUE THREAD

**Issue by DustinBrett** [mlc-ai/web-stable-diffusion#21]
I saw a rather interesting update commit https://github.com/mlc-ai/web-stable-diffusion/commit/2cbd64de4e0a110b4d4749c928598227db2116bb and would like to try it out, but I have an RX 580 and couldn't get it to build without CUDA in WSL. Could someone do a dist build and/or update the github pages example?

Thanks!

**Comment by MasterJH5574** [comment]
Hi @DustinBrett, we have just launched a GitHub Page deployment. You can go to the demo site and check it out now :-)

**Comment by DustinBrett** [comment]
Great! Thanks very much! I will get to integrating this. I am hoping the async shader loader will help my initial loading speeds in Windows.

**Comment by DustinBrett** [comment]
The new build is so much faster (almost 2 mins, on first load) on my Windows machine. Thanks!
