### ISSUE TITLE
[bug] "ms.database.create(work_dir=args.db_path)", JSONReader: cannot find field purity

### ISSUE THREAD

**Issue by felixslu** [mlc-ai/web-stable-diffusion#38]
root@Precision-3660:web-stable-diffusion# python3 build.py --target cuda
Load cached module from dist/mod_cache_before_build.pkl and skip tracing. You can use --use-cache=0 to retrace
Traceback (most recent call last):
  File "web-stable-diffusion/build.py", line 175, in <module>
    build(mod, ARGS)
  File "web-stable-diffusion/build.py", line 136, in build
    db = ms.database.create(work_dir=args.db_path)
  File "/root/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/tvm/meta_schedule/database/database.py", line 417, in create
    return JSONDatabase(*args, **kwargs)
  File "/root/miniconda3/envs/mlc-llm/lib/python3.10/site-packages/tvm/meta_schedule/database/json_database.py", line 86, in __init__
    self.__init_handle_by_constructor__(
  File "tvm/_ffi/_cython/./object.pxi", line 132, in tvm._ffi._cy3.core.ObjectBase.__init_handle_by_constructor__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 287, in tvm._ffi._cy3.core.ConstructorCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 276, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./base.pxi", line 181, in tvm._ffi._cy3.core.CHECK_CALL
ValueError: Traceback (most recent call last):
  4: TVMFuncCall
  3: _ZN3tvm7runtime13PackedFun
  2: tvm::runtime::TypedPackedFunc<tvm::meta_schedule::Database (tvm::runtime::String, tvm::runtime::String, bool, tvm::runtime::String)>::AssignTypedLambda<tvm::meta_schedule::Database (*)(tvm::runtime::String, tvm::runtime::String, bool, tvm::runtime::String)>(tvm::meta_schedule::Database (*)(tvm::runtime::String, tvm::runtime::String, bool, tvm::runtime::String), std::string)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*) const
  1: tvm::meta_schedule::Database::JSONDatabase(tvm::runtime::String, tvm::runtime::String, bool, tvm::runtime::String)
  0: tvm::meta_schedule::Workload::FromJSON(tvm::runtime::ObjectRef const&) [clone .cold]
  8: TVMFuncCall
  7: _ZN3tvm7runtime13PackedFun
  6: tvm::runtime::TypedPackedFunc<tvm::meta_schedule::Database (tvm::runtime::String, tvm::runtime::String, bool, tvm::runtime::String)>::AssignTypedLambda<tvm::meta_schedule::Database (*)(tvm::runtime::String, tvm::runtime::String, bool, tvm::runtime::String)>(tvm::meta_schedule::Database (*)(tvm::runtime::String, tvm::runtime::String, bool, tvm::runtime::String), std::string)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}::operator()(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*) const
  5: tvm::meta_schedule::Database::JSONDatabase(tvm::runtime::String, tvm::runtime::String, bool, tvm::runtime::String)
  4: tvm::meta_schedule::Workload::FromJSON(tvm::runtime::ObjectRef const&)
  3: tvm::LoadJSON(std::string)
  2: tvm::JSONAttrSetter::Set(tvm::runtime::ObjectPtr<tvm::runtime::Object>*, tvm::JSONNode*)
  1: void tvm::JSONAttrSetter::ParseValue<bool>(char const*, bool*) const
  0: tvm::JSONAttrSetter::GetValue(char const*) const [clone .part.0]
  File "/workspace/tvm/src/meta_schedule/database/database.cc", line 66
ValueError: **Unable to parse the JSON object**: ["4686030152544265303", "UqcAAAAAAAB..."
The error is: [19:14:28] /workspace/tvm/src/node/serialization.cc:375: **JSONReader: cannot find field purity**

![Uploading image.png…]()

**Comment by MasterJH5574** [comment]
Fixed in #42 :-)

**Comment by sidsingla** [comment]
Hi:)
With the latest code and #42 fix, I am facing the same issue (Tried it out today).
Thanks!
