### ISSUE TITLE
Update stable diffusion log_db (database) for  the newly introduced purity flag

### ISSUE THREAD

**Issue by felixslu** [mlc-ai/web-stable-diffusion#40]
hi,MLC Team!
Could you have time to  update the stable diffusion log_db ? 
Because, we can not get auto-tunning params for newly  introduced purity flag. We get error below when do "ms.database.create" ops.

/workspace/tvm/src/node/serialization.cc:375: JSONReader: cannot find field purity

**Comment by Michellejia** [comment]
I have the same error. Would really appreciate it if you could update the folder!

**Comment by MasterJH5574** [comment]
Hi @felixslu and @Michellejia, thanks for your feedback! The database has been fixed by #42 with local test. I would appreciate if you could try out the build. Sorry for the delaying response.

**Comment by felixslu** [comment]
> Hi @felixslu and @Michellejia, thanks for your feedback! The database has been fixed by #42 with local test. I would appreciate if you could try out the build. Sorry for the delaying response.

Thanks a lot! We run it on our target device now after your updates!


Could you guide us to auto tune the SD v1.5 model  as mentioned in this issue? https://github.com/mlc-ai/web-stable-diffusion/issues/39
because we want to deploy it on other devices,such as mobile phones.

**Comment by tqchen** [comment]
Closing for now as original issue is resolved, feel free to open a new issue

**Comment by Civitasv** [comment]
> The database has been fixed by #42 with local test.

Hello, @MasterJH5574. Could you please share the script you are using? I would like to obtain the tune records myself.
