### ISSUE TITLE
Quality of the image is poor.

### ISSUE THREAD

**Issue by sunzj** [mlc-ai/web-stable-diffusion#60]
I try sd1.5 and SDXL, the result seems dont as i expected. 

i tried the following prompt on sdxl, 
https://anakin.ai/blog/sdxl-photorealistic-prompts/

expected result are:
![image](https://github.com/mlc-ai/web-stable-diffusion/assets/5491518/6d2e42d1-3f61-4f2e-a2a5-57f8be619822)

![image](https://github.com/mlc-ai/web-stable-diffusion/assets/5491518/08bffb4a-d4f4-455b-af4b-23153c20234c)

but the  result are blur and low quality.

I am not sure it's my config problem or it's a common issue.

**Comment by happyme531** [comment]
I think on SDXL the issue is it is using vae config of sd1.5

https://github.com/happyme531/RK3588-stable-diffusion-GPU/blob/37957e25e3af6d959165829a1483e3c5416fcfc8/web_stable_diffusion/trace/model_trace.py#L93

And on SD1.5 the issue is the vae scale is wrong (see the commit in the above link)

**Comment by sunzj** [comment]
@happyme531  could you share your result with prompt  on XL: "A breathtaking panorama of Melbourne Beach at dusk. The golden sun dips below the horizon, casting a warm glow on the endless stretch of pristine white sand. Gentle waves lap at the shore, their rhythmic sound mingling with the cries of seagulls soaring overhead. Palm trees sway gently in the breeze, casting long shadows on the beach. In the distance, the iconic Melbourne Beach Pier stretches out into the ocean, silhouetted against the vibrant hues of the setting sun. The air is filled with the salty scent of the ocean and the feeling of peace and tranquility. "

here is my result, it seems better, but isn't enough.
![sea](https://github.com/mlc-ai/web-stable-diffusion/assets/5491518/99b8e89d-d90b-4766-a5ce-792a485b131e)
